[project]
name = "djquickstart"
version = "0.1.0"
description = "CLI tool for fast Django project setup"
authors = [{name="You"}]
dependencies = ["click", "Django"]

[project.scripts]
djquickstart = "djquickstart.cli:cli"
